# generated by datamodel-codegen:
#   filename:  get_member_profile.json
#   timestamp: 2024-12-07T16:55:58+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ProjectDefaultValue(BaseModel):
    projectId: str
    status: str
    value: str


class CustomField(BaseModel):
    allowedValues: List[str]
    description: str
    entityType: str
    id: str
    name: str
    onlyAdminCanEdit: bool
    placeholder: str
    projectDefaultValues: List[ProjectDefaultValue]
    required: bool
    status: str
    type: str
    workspaceDefaultValue: str
    workspaceId: str


class UserCustomFieldValue(BaseModel):
    customField: CustomField
    customFieldId: str
    name: str
    sourceType: str
    type: str
    userId: str
    value: str


class Member(BaseModel):
    email: str
    hasPassword: bool
    hasPendingApprovalRequest: bool
    imageUrl: str
    name: str
    userCustomFieldValues: List[UserCustomFieldValue]
    weekStart: str
    workCapacity: str
    workingDays: List[str] | str
    workspaceNumber: int
