# generated by datamodel-codegen:
#   filename:  get_logged_in_user.json
#   timestamp: 2024-11-22T22:38:10+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, RootModel


class CustomField(BaseModel):
    customFieldId: str
    customFieldName: str
    customFieldType: str
    userId: str
    value: str


class CostRate(BaseModel):
    amount: int
    currency: str


class HourlyRate(BaseModel):
    amount: int
    currency: str


class Membership(BaseModel):
    costRate: CostRate
    hourlyRate: HourlyRate
    membershipStatus: str
    membershipType: str
    targetId: str
    userId: str


class SummaryReportSettings(BaseModel):
    group: str
    subgroup: str


class Settings(BaseModel):
    alerts: bool
    approval: bool
    collapseAllProjectLists: bool
    dashboardPinToTop: bool
    dashboardSelection: str
    dashboardViewType: str
    dateFormat: str
    groupSimilarEntriesDisabled: bool
    isCompactViewOn: bool
    lang: str
    longRunning: bool
    multiFactorEnabled: bool
    myStartOfDay: str
    onboarding: bool
    projectListCollapse: int
    projectPickerTaskFilter: bool
    pto: bool
    reminders: bool
    scheduledReports: bool
    scheduling: bool
    sendNewsletter: bool
    showOnlyWorkingDays: bool
    summaryReportSettings: SummaryReportSettings
    theme: str
    timeFormat: str
    timeTrackingManual: bool
    timeZone: str
    weekStart: str
    weeklyUpdates: bool


class User(BaseModel):
    activeWorkspace: str
    customFields: List[CustomField]
    defaultWorkspace: str
    email: str
    id: str
    memberships: List[Membership]
    name: str
    profilePicture: str
    settings: Settings
    status: str


class Users(RootModel[List[User]]):
    root: List[User]
